version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jat-facturacion-ar"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xlyz6lsg0ext"
s3_prefix = "jat-facturacion-ar"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
